apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.34.0
directories:
# doc: https://carvel.dev/vendir/docs/v0.35.x/vendir-spec/

- path: src/github.com
  contents:

  - path: etcd-io/etcd
    githubRelease:
      slug: etcd-io/etcd 
      tag: v3.6.5
      disableAutoChecksumValidation: true
      assetNames: # only download specific assets (optional; v0.12.0+). We use assetNames inside githubRelease instead of
      # includePaths at path level. Using includePaths downloads all assets and filter after.
      - "etcd-v*-linux-amd64.tar.gz"
    # includePaths: # includes paths specify what should be included. by default all paths are included (optional)

